### ISSUE TITLE
NoMethodError: undefined method `fetched?'

### ISSUE THREAD

**Issue by npaufler** [Shopify/shipit-engine#802]
``2018-06-14T23:13:52.640Z 28179 TID-osn726p9j Shipit::CacheDeploySpecJob JID-cc615786bdeac9a733705177 INFO: fail: 0.015 sec
2018-06-14T23:13:52.640Z 28179 TID-osn726p9j WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Shipit::CacheDeploySpecJob","queue":"default","args":[{"job_class":"Shipit::CacheDeploySpecJob","job_id":"6a42fa07-0ceb-4c66-b192-c9d964e85772","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://deploy-clio-systems/Shipit::Stack/1"}],"executions":0,"locale":"en"}],"retry":true,"jid":"cc615786bdeac9a733705177","created_at":1529017423.0174057,"enqueued_at":1529018032.6230292,"error_message":"undefined method `fetched?' for #<Shipit::StackCommands:0x00007fd13c873420>\nDid you mean?  fetch","error_class":"NoMethodError","failed_at":1529017424.485073,"retry_count":3,"retried_at":1529017883.4487817},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Shipit::CacheDeploySpecJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"Shipit::CacheDeploySpecJob\",\"job_id\":\"6a42fa07-0ceb-4c66-b192-c9d964e85772\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://deploy-clio-systems/Shipit::Stack/1\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"cc615786bdeac9a733705177\",\"created_at\":1529017423.0174057,\"enqueued_at\":1529018032.6230292,\"error_message\":\"undefined method `fetched?' for #<Shipit::StackCommands:0x00007fd13c873420>\\nDid you mean?  fetch\",\"error_class\":\"NoMethodError\",\"failed_at\":1529017424.485073,\"retry_count\":3,\"retried_at\":1529017883.4487817}"}
2018-06-14T23:13:52.640Z 28179 TID-osn726p9j WARN: NoMethodError: undefined method `fetched?' for #<Shipit::StackCommands:0x00007f3da0095a58>
Did you mean?  fetch
``

After upgrading to 0.23.0 the other day, our sidekiq log is full of the above error. Unclear to me if this is a bug in ShipIt or if it's an artifact of the upgrade.

Does anyone have any suggestions on what we should check?

Thanks

**Comment by casperisfine** [comment]
This is an actual bug. I've fixed it and just released a `0.23.1`, thank you very much for reporting it!
